# This is a config for E2B sandbox template.
# You can use template ID (hnt99hojqohbhbj9jjck) or template name (vibe-code) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-code") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-code") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-code')

team_id = "97b38675-48b9-43fa-9faa-3fe324626671"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-code"
template_id = "hnt99hojqohbhbj9jjck"
